### ISSUE TITLE
Multiple NullPointerException

### ISSUE THREAD

**Issue by yleyvag** [ZetDeveloper/MultimediaPicker#2]
With this code:

```
MultimediaPicker.create(this)
                .folderMode(true)
                .folderTitle(getString(R.string.folder_video))
                .setOnlyVideos(true)
                .single()
                .showCamera(false)
                .start(REQUEST_CODE_VIDEO_PICKER);
```
Never shows the Activity, the app crashed, in the Log I'm receiving:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.widget.RecyclerView$Adapter android.support.v7.widget.RecyclerView.getAdapter()' on a null object reference
                                                                            at com.zet.enterprises.multimediapicker.ContainerFragment.isDisplayingFolderView(ContainerFragment.java:553)
                                                                            at com.zet.enterprises.multimediapicker.GalleryPickerActivity.updateTitle(GalleryPickerActivity.java:269)
                                                                            at com.zet.enterprises.multimediapicker.GalleryPickerActivity.onCreateOptionsMenu(GalleryPickerActivity.java:255)
                                                                            at android.app.Activity.onCreatePanelMenu(Activity.java:3127)

With this code:

```
MultimediaPicker.create(this)
                .folderMode(false)
                .folderTitle(getString(R.string.folder_video))
                .imageTitle(getString(R.string.touch_for_select))
                .setOnlyVideos(true)
                .single()
                .showCamera(false)
                .start(REQUEST_CODE_VIDEO_PICKER);
```
shows the Activity but the back button crash the app, the Log shows:

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.setResult(int)' on a null object reference
                                                                            at com.zet.enterprises.multimediapicker.ContainerFragment.onBackPressed(ContainerFragment.java:570)
                                                                            at com.zet.enterprises.multimediapicker.GalleryPickerActivity.onBackPressed(GalleryPickerActivity.java:390)
                                                                            at com.zet.enterprises.multimediapicker.GalleryPickerActivity.onOptionsItemSelected(GalleryPickerActivity.java:322)
                                                                            at android.app.Activity.onMenuItemSelected(Activity.java:3204)

Showing only videos screen is causing too much troubles. I really liked this library, I hope problems get solved.

**Comment by axionnneeeel** [comment]
Hello. I faced the same problem and you have to modify the source code. If you select videos only indexTab will be 0 but videos are for indexTab = 1. Try to modify the source code to fit your needs.
